backend:
  name: github
  repo: GiovanniFerrara/alessandrorlando.it
media_folder: static/img/upload
public_folder: /img/upload

collections:
  - name: "homepage"
    label: "Pages"
    files:
    - file: "content/pages/homepage.yaml"
      create: false
      editor: 
        preview: false 
      name: homepage
      label: Home Page
      delete: false
      fields:
        - {label: "background Homepage Desktop", name: "backgroundDesktop", widget: "image"}
        - {label: "background Homepage Mobile", name: "backgroundMobile", widget: "image"}
    - file: "content/pages/commons.yaml"
      create: false
      editor: 
        preview: false 
      name: commons
      label: General Settings
      delete: false
      fields:
        - {label: "background Desktop", name: "backgroundDesktop", widget: "image"}
        - {label: "background Mobile", name: "backgroundMobile", widget: "image"}
    - file: "content/pages/video.yaml"
      editor: 
        preview: false 
      delete: false
      name: video
      label: Video Page
      fields:
        - {label: "Clip Category label", name: "titleClip", widget: "string"}
        - {label: "Clip Cover photo", name: "coverClip", widget: "image"}
        - {label: "Stage Category label", name: "titleStage", widget: "string"}
        - {label: "Stage Cover photo", name: "coverStage", widget: "image"}
        - {label: "Home Videos Category label", name: "titleHome", widget: "string"}
        - {label: "Stage Cover photo", name: "coverHome", widget: "image"}

    - file: "content/pages/photography.yaml"
      create: false
      editor: 
        preview: false 
      name: photography
      label: Photography Page
      delete: false
      fields:
        - {label: "Behind Cover Picture", name: "behind", widget: "image"}
        - {label: "In Front Cover Picture", name: "infront", widget: "image"}
    - file: "content/pages/concertsevents.md"
      create: false
      editor: 
        preview: false
        remove: false 
      name: concertsevents
      label: Concerts & Events Page
      delete: false
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Content", name: "body", widget: "markdown"}
  - name: photography
    label: Album
    folder: content/photography/
    slug: "{{slug}}"
    editor: 
      preview: false 
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover Picture", name: "cover", widget: "image"}
      - {label: "Category lowercase or minuscolo, one of (infront - behind)", name: "category", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "photography"}
  - name: video
    label: Videos
    folder: content/video/
    slug: "{{slug}}"
    editor: 
      preview: false 
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link for embedded videos", name: "link", widget: "string"}
      - {label: "Category lowercase or minuscolo, one of (home - stage - clip)", name: "category", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "video"}

  - name: music
    label: Music Albums
    folder: content/music/
    slug: "{{slug}}"
    editor: 
      preview: false 
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Album cover", name: "cover", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "music"}
      - label: Songs List
        name: songs
        widget: list
        allow_add: true
        fields: 
          - {label: "title", name: "title", widget: "string"}
          - {label: "link", name: "link", widget: "string"}
          - {label: "text", name: "text", widget: "markdown"}