backend:
  name: github
  repo: GiovanniFerrara/alessandrorlando.it
media_folder: static/img
public_folder: /img/upload

collections:
  - name: "homepage"
    label: "Home Page"
    files:
    - file: "content/pages/homepage.yaml"
      create: false
      editor: 
      name: homepage
      label: Homepage
      delete: false
      preview: false 
      slug: "{{year}}-{{month}}-{{day}}-{{}}_{{slug}}"
      fields:
        - {label: "backgroundDesktop", name: "backgroundDesktop", widget: "image"}
        - {label: "backgroundMobile", name: "backgroundMobile", widget: "image"}
    - file: "content/pages/commons.yaml"
      create: false
      editor: 
      name: commons
      label: General Settings
      delete: false
      preview: false 
      slug: "{{year}}-{{month}}-{{day}}-{{}}_{{slug}}"
      fields:
        - {label: "backgroundDesktop", name: "backgroundDesktop", widget: "image"}
        - {label: "backgroundMobile", name: "backgroundMobile", widget: "image"}